language: scala
sudo: required
dist: trusty

scala:
  - 2.11.11

jdk:
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.3
    jdk: oraclejdk8

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.nvm

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - pip install --user codecov
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean testsJS/test; #todo: combine the two tests on scalajs after https://github.com/scalameta/paradise/issues/201 is fixed.
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM;
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
